Final Project/SECsite/SECsite/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('users/', include('accounts.urls')),
	#path('SECforms/', include('SECforms.urls')),
	path('',views.main_page, name="mainPage"),
	]

Final Project/SECsite/accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('register', views.register, name='register_user'),
    path('company', views.company_page, name='company_page'),
    path('settings', views.settings_page, name='settings_page'),
]

Final Project/SECsite/SECforms/models.py
from django.db import models

# Create your models here.

Final Project/SECsite/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.db.models.fields import CharField, DateField, EmailField
from django.db.models.fields.related import ForeignKey
# Create your models here.

class Note(models.Model):
    text_content = models.CharField(blank=True, editable=True, max_length=500)
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE)


class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    employed_by=models.ForeignKey('Firm', on_delete=models.PROTECT)
    employee_mail= EmailField(blank=True, null=True)
    

class Firm(models.Model):
    name=CharField(max_length=200)


class Client(models.Model):
    name=CharField(max_length=200)
    firm=ForeignKey(Firm, on_delete=models.CASCADE)
    yearly= DateField(blank=True, null=True)
    first_quarter= DateField(blank=True, null=True)
    second_quarter= DateField(blank=True, null=True)
    third_quarter= DateField(blank=True, null=True)
    client_mail= EmailField(blank=True, null=True)

Final Project/SECsite/accounts/forms.py
from django import forms
from django.db.models import fields
from .models import Client



class NewUserForm(forms.Form):
    username=forms.CharField(max_length=200)
    password=forms.CharField(max_length=200, widget=forms.PasswordInput)





class NewClientForm(forms.ModelForm):
    class Meta:
        model=Client
        exclude=['firm']


class NewNoteForm(forms.ModelForm):
    # text_content = forms.CharField(blank=True, editable=True, widget=forms.Textarea(attrs={"rows":5, "cols":20}))
    text_content = forms.CharField(widget=forms.Textarea, max_length=500)

Final Project/SECsite/SECforms/views.py
from django.shortcuts import render

# Create your views here.

Final Project/SECsite/accounts/views.py
from django.http import request
from django import forms, template
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpRequest
from django.contrib.auth import authenticate, login, decorators
from .forms import NewUserForm, NewClientForm, NewNoteForm
from .models import Client, Profile
from django.contrib.auth.models import User

def login_view(request):
    if request.method=='POST':
        print('request POST error')
        print(request.POST)
        user=authenticate(username=request.POST.get('userNameInput'), password=request.POST.get('passwordInput'))
        if user:
            login(request, user)
             #send us to relevant company page
            return redirect('company_page')

    return render(request,'login.html')


def main_page(request):
    if request.method=='POST':
        print('request POST error')
        print(request.POST)

    return render(request, 'mainPage.html')

@decorators.login_required
def register(request):
    form = NewUserForm()
    if request.method=='POST':
        form=NewUserForm(request.POST)
        if form.is_valid():
            user=User.objects.create_user(**form.cleaned_data)
            profile=Profile.objects.create(user=user, employed_by=request.user.profile.employed_by)
             #redirect to relevant company page
            return redirect('company_page')

    return render(request, 'register.html', {'f':form, 'object_type':'new Employee'})


@decorators.login_required
def company_page(request):

    form = NewClientForm()
    if request.method=='POST':
        form=NewClientForm(request.POST)
        if form.is_valid():
            client= form.save(commit=False)
            client.firm=request.user.profile.employed_by
            client.save()
            #redirect to relevant company page
            return redirect('mainPage')

    return render(request, 'companyPage.html', {'f':form, 'object_type':'client'})



@decorators.login_required
def new_note(request):

    form = NewNoteForm()
    if request.method=='POST':
        form=NewNoteForm(request.POST)
        if form.is_valid():
            note= form.save(commit=False)
            # note.Profile=request.user.profile.employed_by
            note.save()
            #redirect to relevant company page
            return redirect('mainPage')

    return render(request, 'companyPage.html', {'f':form, 'object_type':'client'})





@decorators.login_required
def settings_page(request):
    return render(request, 'settings.html')

Final Project/SECsite/accounts/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		{% block css %}{% endblock %}
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	</head>
	<body>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<a class="navbar-brand" href="{%url 'login_view'%}">Login</a>
				<a class="navbar-brand" href="{%url 'register_user'%}">Register New</a>
				<a class="navbar-brand" href="{%url 'settings_page'%}">Settings</a>
				<a class="navbar-brand" href="{%url 'mainPage'%}">Logout</a>
			</div>
		</nav>
		{% block content %}{% endblock %}
	</body>
</html>

Final Project/SECsite/accounts/templates/clientPopup.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Add Client {{type}}
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New Client</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST">
          <div class="modal-body">
                  {%csrf_token%}
                {{clientForm.as_p}}
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Save</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          
        </div>
      </form>
      </div>
    </div>
  </div>

Final Project/SECsite/accounts/templates/companyPage.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{user.profile.employed_by.name}} {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'accounts/css/tester.css' %}">
<link rel="stylesheet" href="{% static 'accounts/css/myCSS.css' %}">
<link rel="stylesheet" href="{% static 'accounts/js/resizeJS.js' %}">
<link rel="stylesheet" href="{% static 'accounts/js/dateCheck.js' %}">
 {% endblock %}
{% block content %}




{#<!-- Main Page Section> -->#}
<div class="container-fluid d-flex justify-content-end" style="background-color: gainsboro; display: flex; height: 100vh; width: 100vw;">
  <div class="row">
          {#<!-- Left half of page -->#}
              <div class="col-sm col-md col-xl flex-column d-flex align-items-stretch" style="border: black solid; width: 100vw;">
                <div class="row d-flex flex-column" style="background-color: whitesmoke;">
                    <h1 style="text-align: center;">Hello {% block name %} {{user.username}}  {% endblock %} welcome back</h1>
                    <br>
                    <br>
                    {%for client in user.profile.employed_by.client_set.all%}
                    <a href="#" class="card">{{client.name}} filing due in 3 Months</a>
                    {%endfor%}
                    <br>
                    <br>
                    <br>
                    <br>
                </div>
<br>
                <div class="row d-flex flex-column" style="background-color: wheat;">
                  <h1 style="text-align: center; background-color: #f8d490;">Personal Notepad</h1>
                 {% include 'notePopup.html' with noteForm=f %}              
                  {%for notes in user.profile.notes.note_set.all%}
                  <br>
                  <br>
                  <br>
                  <br>
                  {%endfor%}

                  <br>
                  <br>
                </div>
            </div>



            {#<!-- Right half of page -->#}
          <div class="panel-body panel-resizable position-fixed-right" style="border-left: black thick;">

            {#<!--This is the Add Client code -->#}
            <div class="row align-items-end" style="background-color: #95A5A6;">
              {% include 'clientPopup.html' with clientForm=f %}
            </div>




            {#<!--Print all Clients -->#}
              {%for client in user.profile.employed_by.client_set.all%}


              <div class="list-group overflow-auto" style="width: 18rem;">
                  <div class="cardStyle">
                    <h5 class="card-title">{{client.name}}</h5>
                    <a href="#" class="card-link">Open</a>
                    <button> </button>
                </div>
              {%endfor%}
          </div>
  
              </div>
          </div>
  </div> 
</div>




{% endblock %}

Final Project/SECsite/accounts/templates/homePage.html
{% extends "base.html" %}
{% block title %}Company Main Page{% endblock %}
{% block content %}
<h1>Homepage</h1>


{% endblock %}

Final Project/SECsite/accounts/templates/login.html
{% extends "base.html" %}
{% block title %}Login Page{% endblock %}
{% block content %}
<h1>Login</h1>
<form method="POST">
    {%csrf_token%}
    <input type="text" name="userNameInput">
    <input type="password" name="passwordInput">
    <button>Login</button>
    
</form>

{% endblock %}

Final Project/SECsite/accounts/templates/notePopup.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModal2">
    + Add Note {{type}}
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModal2Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModal2Label">New Note</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="POST">
          <div class="modal-body">
                  {%csrf_token%}
            <textarea name="new_note" id="" cols="30" rows="10"></textarea>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Save</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          
        </div>
      </form>
      </div>
    </div>
  </div>

Final Project/SECsite/accounts/templates/register.html
{% extends "base.html" %}
{% block title %}Add {{object_type}} {% endblock %}
{% block content %}


<h1>Create {{object_type}}</h1>
<form method="POST">
{%csrf_token%}
{{f.as_p}}

  <div class="form-check">
    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
    <label class="form-check-label" for="invalidCheck">
        I have read and agree to the 
        <a href="#" class="link-primary">Terms and Conditions</a>
    </label>
    <div class="invalid-feedback">
      You must agree before submitting.
    </div>
  </div>

<button>Register</button>
</form>

{% endblock %}

Final Project/SECsite/accounts/templates/settings.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{user.profile.name}} 'User Settings' {% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'accounts/css/myCSS.css' %}">
 {% endblock %}






 {% block content %}
<div class="fluid-container" style="background-color: burlywood; height: 100vh; text-align: center;">
    <input type="checkbox" checked data-toggle="toggle" data-on="Hello<br>World" data-off="Goodbye<br>World">


<input type="toggle-switch" checked data-toggle="toggle" data-onstyle="primary">
<br>
<input type="checkbox" checked data-toggle="toggle" data-onstyle="secondary">
<br>
<input type="checkbox" checked data-toggle="toggle" data-on="Ready" data-off="Not Ready" data-onstyle="success" data-offstyle="danger">
<input type="checkbox" checked data-toggle="toggle" data-onstyle="success">
<br>
</div>


{% endblock %}